### PR TITLE
Add Thai translation

### PR DESCRIPTION
**Pull request by byhbt**
### Summary of changes

Add Thai translation

"Plural-Forms: nplurals=1; plural=0;\n" means one single form. There is no distinction between the singular and plural form.

Reference: 
- https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html

### CODE REVIEW

**Review by Lahphim — APPROVED** [review]
All good to me 🙌
But there is one thing I raise to @rosle, which is about this here.
```
msgstr[0] "%{count} เดือนที่แล้ว"
msgstr[1] "%{count} เดือนที่แล้ว"
```
In Thai, we don't have the plural terms, so can we omit that out or the other option 🤔

cc: @byhbt

**Comment by byhbt** [comment]
> All good to me 🙌
> But there is one thing I raise to @rosle, which is about this here.
> 
> ```
> msgstr[0] "%{count} เดือนที่แล้ว"
> msgstr[1] "%{count} เดือนที่แล้ว"
> ```
> 
> In Thai, we don't have the plural terms, so can we omit that out or the other option 🤔
> 
> cc: @byhbt

hi @Lahphim and @rosle !

I just research a bit about that issue. As the docs here: https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html, it said: 

image

So I think in this case we need: 

Add this header to the top of file `priv/translations/th/LC_MESSAGES/relative_time.po` .`"Plural-Forms: nplurals=1; plural=0;\n"`

Then we can remove the msgstr[1] just keep msgstr[0]

**Other references:**
- https://www.drupal.org/community/contributor-guide/reference-information/localize-drupal-org/working-with-offline/po-and#s-plural-forms
- https://www.gnu.org/software/gettext/manual/html_node/Translating-plural-forms.html
- https://haptiq.studio/plural-forms/

**Comment by byhbt** [comment]
hi @rosle and @Lahphim !
I just check another library (elixir-cldr) that has a translation for `am` and `pm` in the `priv/translations/th/LC_MESSAGES/day_periods.po`, but not sure is it applicable for our case? 🤔 

https://raw.githubusercontent.com/elixir-cldr/cldr/master/priv/cldr/locales/th.json

image

**Comment by Lahphim** [comment]
> hi @rosle and @Lahphim !
> I just check another library (elixir-cldr) that has a translation for `am` and `pm` in the `priv/translations/th/LC_MESSAGES/day_periods.po`, but not sure is it applicable for our case? 🤔
> 
> https://raw.githubusercontent.com/elixir-cldr/cldr/master/priv/cldr/locales/th.json
> 
> image

@byhbt IMO, it looks weird to use `am` and `pm` terms in Thai 🤔
Because if we want to use that it would we different thing from the `am/pm` period of time.
For example:
`1 am` -> `ตี 1`
`7 am` -> `7 โมงเช้า`
`1 pm` -> `บ่าย 1`
`7 pm` -> `1 ทุ่ม`
😵
And if we want to use the word from your link it will be like these.
`1 am` -> `1 ก่อนเที่ยง`
`7 am` -> `7 ก่อนเที่ยง`
`1 pm` -> `1 หลังเที่ยง`
`7 pm` -> `7 หลังเที่ยง`
which are no meaning in Thai but we can understand of those above.
I think for this case it if we use timestamp with `24hrs` format, it would solve this issue because we can use something like these.
 `1 am` -> `01.00  น.`
`7 am` -> `07.00  น.`
`1 pm` -> `13.00  น.`
`7 pm` -> `19.00  น.`

cc: @rosle

**Comment by byhbt** [comment]
hi @Lahphim 

Yup, i checked the project requirement, for the date time format in Thai locale, it's `{day} {month} {year_buddhist} {time_24_hrs}`. It does NOT include the `am/pm` there.

Thank you very much for the feedback! 🙏 

It seems good to go without that.

**Review by andyduong1920 — APPROVED** [review]

**Comment by andyduong1920** [comment]
Thanks @rosle @Lahphim and @byhbt 👍

**Pull request merged**
